Repository kubernetes-sigs/wg-device-management, pull requests merged in 2024-05, with the labels that each got.

#2 Add pools-only model
  k8srm-prototype/.gitignore
  k8srm-prototype/Makefile
  k8srm-prototype/README.md
  k8srm-prototype/allocation_types.go
  k8srm-prototype/capacity_types.go
  k8srm-prototype/cel.go
  k8srm-prototype/claim_types.go
  k8srm-prototype/cmd/mock-apiserver/main.go
  k8srm-prototype/cmd/schedule/main.go
  k8srm-prototype/gen.go
  k8srm-prototype/go.mod
  k8srm-prototype/go.sum
  k8srm-prototype/kubeconfig
  k8srm-prototype/main.go
  k8srm-prototype/pkg/api/capacity_types.go
  k8srm-prototype/pkg/api/claim_types.go
  k8srm-prototype/pkg/gen/gen.go
  k8srm-prototype/pkg/schedule/cel.go
  k8srm-prototype/pkg/schedule/cel_test.go
  k8srm-prototype/pkg/schedule/result_types.go
  k8srm-prototype/pkg/schedule/schedule.go
  k8srm-prototype/pkg/schedule/schedule_test.go
  k8srm-prototype/schedule.go
  k8srm-prototype/schedule_test.go
  k8srm-prototype/schedulepod_test.go
  k8srm-prototype/testdata/classes.yaml
  k8srm-prototype/testdata/drivers.yaml
  k8srm-prototype/testdata/node-large-16x128-numa-0.yaml
  k8srm-prototype/testdata/node-large-16x128x8-foozer4000-numa-0.yaml
  k8srm-prototype/testdata/node-medium-8x64-numa-0.yaml
  k8srm-prototype/testdata/node-medium-8x64x4-foozer1000-numa-0.yaml
  k8srm-prototype/testdata/node-small-2x8-0.yaml
  k8srm-prototype/testdata/node-small-4x32-0.yaml
  k8srm-prototype/testdata/node-small-4x32-numa-0.yaml
  k8srm-prototype/testdata/node-tiny-1x1-0.yaml
  k8srm-prototype/testdata/node-tiny-1x2-0.yaml
  k8srm-prototype/testdata/node-tiny-1x2x1-foozer1000-0.yaml
  k8srm-prototype/testdata/pod-1x100mx100Mi.yaml
  k8srm-prototype/testdata/pod-besteffort-1x0.yaml
  k8srm-prototype/testdata/pod-container-small-foozer-1-8.yaml
  k8srm-prototype/testdata/pod-container-small-foozer-16-32.yaml
  k8srm-prototype/testdata/pod-embedded-foozer-single.yaml
  k8srm-prototype/testdata/pod-four-containers.yaml
  k8srm-prototype/testdata/pod-ref-foozer-single.yaml
  k8srm-prototype/testdata/pod-small-1x2-exclusive-foozer.yaml
  k8srm-prototype/testdata/pod-template-foozer-single.yaml
  k8srm-prototype/testdata/pod-three-containers.yaml
Labels: cncf-cla: yes, approved

#4 Fix package names
  k8srm-prototype/README.md
  k8srm-prototype/cmd/schedule/main.go
  k8srm-prototype/go.mod
  k8srm-prototype/pkg/gen/gen.go
  k8srm-prototype/pkg/schedule/cel.go
  k8srm-prototype/pkg/schedule/cel_test.go
  k8srm-prototype/pkg/schedule/result_types.go
  k8srm-prototype/pkg/schedule/schedule.go
  k8srm-prototype/pkg/schedule/schedule_test.go
Labels: size/M, cncf-cla: yes, approved

#6 Add prototype that extends NamedResources for partitionable devices
  nv-partitionable-devices/.gitignore
  nv-partitionable-devices/Makefile
  nv-partitionable-devices/README.md
  nv-partitionable-devices/cmd/print-model/main.go
  nv-partitionable-devices/cmd/print-possible-allocations/iterate.go
  nv-partitionable-devices/cmd/print-possible-allocations/main.go
  nv-partitionable-devices/go.mod
  nv-partitionable-devices/go.sum
  nv-partitionable-devices/hack/boilerplate.go.txt
  nv-partitionable-devices/pkg/intrange/.intrange.go.swn
  nv-partitionable-devices/pkg/intrange/intrange.go
  nv-partitionable-devices/pkg/intrange/intrange_test.go
  nv-partitionable-devices/pkg/intrange/zz_generated.deepcopy.go
  nv-partitionable-devices/pkg/nvdevice/nvdevice.go
  nv-partitionable-devices/pkg/resource/current/api.go
  nv-partitionable-devices/pkg/resource/current/convert.go
  nv-partitionable-devices/pkg/resource/new/api.go
  nv-partitionable-devices/pkg/resource/new/convert.go
  nv-partitionable-devices/pkg/resource/new/methods.go
  nv-partitionable-devices/pkg/resource/new/zz_generated.deepcopy.go
Labels: lgtm, size/XXL, cncf-cla: yes, approved

#7 Change the dir name to match the package path
  nv-partitionable-resources/.gitignore
  nv-partitionable-resources/Makefile
  nv-partitionable-resources/README.md
  nv-partitionable-resources/cmd/print-model/main.go
  nv-partitionable-resources/cmd/print-possible-allocations/iterate.go
  nv-partitionable-resources/cmd/print-possible-allocations/main.go
  nv-partitionable-resources/go.mod
  nv-partitionable-resources/go.sum
  nv-partitionable-resources/hack/boilerplate.go.txt
  nv-partitionable-resources/pkg/intrange/.intrange.go.swn
  nv-partitionable-resources/pkg/intrange/intrange.go
  nv-partitionable-resources/pkg/intrange/intrange_test.go
  nv-partitionable-resources/pkg/intrange/zz_generated.deepcopy.go
  nv-partitionable-resources/pkg/nvdevice/nvdevice.go
  nv-partitionable-resources/pkg/resource/current/api.go
  nv-partitionable-resources/pkg/resource/current/convert.go
  nv-partitionable-resources/pkg/resource/new/api.go
  nv-partitionable-resources/pkg/resource/new/convert.go
  nv-partitionable-resources/pkg/resource/new/methods.go
  nv-partitionable-resources/pkg/resource/new/zz_generated.deepcopy.go
Labels: lgtm, cncf-cla: yes, approved, size/XS

#5 Changes based on review feedback
  k8srm-prototype/.gitignore
  k8srm-prototype/Makefile
  k8srm-prototype/cmd/gen/main.go
  k8srm-prototype/cmd/schedule/main.go
  k8srm-prototype/go.mod
  k8srm-prototype/go.sum
  k8srm-prototype/notes-and-open-questions.md
  k8srm-prototype/pkg/api/capacity_types.go
  k8srm-prototype/pkg/api/claim_types.go
  k8srm-prototype/pkg/gen/gen.go
  k8srm-prototype/pkg/gen/nvidia.go
  k8srm-prototype/pkg/schedule/result_types.go
  k8srm-prototype/pkg/schedule/schedule.go
  k8srm-prototype/pkg/schedule/schedule_test.go
  k8srm-prototype/pod-spec-examples.yaml
  k8srm-prototype/testdata/classes.yaml
  k8srm-prototype/testdata/drivers.yaml
  k8srm-prototype/testdata/pod-embedded-foozer-single.yaml
  k8srm-prototype/testdata/pod-one-container-one-gpu.yaml
  k8srm-prototype/testdata/pod-one-container-two-gpus-0.yaml
  k8srm-prototype/testdata/pod-one-container-two-gpus-1.yaml
  k8srm-prototype/testdata/pod-one-container-two-gpus-2.yaml
  k8srm-prototype/testdata/pod-ref-foozer-single.yaml
  k8srm-prototype/testdata/pod-template-foozer-single.yaml
Labels: size/XXL, cncf-cla: yes, approved

#10 Fix go.mod
  k8srm-prototype/go.mod
Labels: cncf-cla: yes, approved, size/XS

#9 Additional PodSpec examples
  k8srm-prototype/pod-spec-examples.yaml
  k8srm-prototype/testdata/claim_source.go
  k8srm-prototype/testdata/pod-two-containers-one-gpu.yaml
  k8srm-prototype/testdata/pod-two-containers-two-gpus-0.yaml
  k8srm-prototype/testdata/pod-two-containers-two-gpus-1.yaml
Labels: size/L, cncf-cla: yes, approved

#12 Add some more open questions
  k8srm-prototype/notes-and-open-questions.md
Labels: size/S, cncf-cla: yes, approved
